import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import cls from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import Link from 'next/link'
import { useSelector } from "react-redux"
import { productSelector } from '@/store/reducers/pruduct/product.slice'

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     {
      <style>
     
    </style>
     }
      <main className={cls.main}>
        <button className={cls.button} onClick={() => {
          router.push("/addproducts")
        }}>GO TO ADD</button>
        <button className={cls.button} onClick={() => {
          router.push("/catalog")
        }}>GO TO CATALOG</button>  
      </main>
    </>
  )
}
